#!/usr/bin/env sh

if [ -n "${MINIFLUX__POSTGRES_HOST}" ]; then
  export DATABASE_URL="postgresql://${MINIFLUX__POSTGRES_USERNAME}:${MINIFLUX__POSTGRES_PASSWORD}@${MINIFLUX__POSTGRES_HOST}:${MINIFLUX__POSTGRES_PORT:-5432}/${MINIFLUX__POSTGRES_DATABASE}?sslmode=${MINIFLUX__POSTGRES_SSLMODE:-require}"
fi

exec "$@"
