---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Run all the linters
'on': workflow_call

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup CUE
        uses: cue-lang/setup-cue@v1.0.0

      - name: "Linter: CUE"
        shell: bash
        run: |-
          cue vet --schema '#Spec' ./apps/*/metadata.json ./metadata.rules.cue

      - name: "Linter: hadolint"
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          annotate: true
          dockerfile: "apps/*/Dockerfile"
          error_level: 1
          # renovate: datasource=github-releases depName=hadolint/hadolint
          version: 2.12.0

      - name: "Linter: shellcheck"
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          # renovate: datasource=github-releases depName=koalaman/shellcheck
          version: v0.9.0

      - name: "Linter: yamllint"
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: true
          yamllint_config_filepath: ./.yamllint
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
