---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Validate pull request
'on': pull_request

jobs:
  lint:
    uses: dexters-ops/containers/.github/workflows/lint.yaml@master
    secrets: inherit

  test:
    uses: dexters-ops/containers/.github/workflows/test.yaml@master
    secrets: inherit
